In [1]:
import numpy as np

1. Given a 1D array, negate all elements which are between 3 and 8, in place (not created a new array).

In [19]:
x = np.arange(10)

In [20]:
x

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [22]:
x[(x > 3) & (x < 8)] *= -1

In [23]:
x

array([ 0,  1,  2,  3, -4, -5, -6, -7,  8,  9])

2. Create random vector of size 10 and replace the maximum value by 0

In [43]:
x = np.random.randint(1, 10, 10)

In [44]:
x

array([6, 4, 2, 7, 9, 7, 4, 6, 7, 6])

In [45]:
x[x.argmax()] = 0

In [46]:
x

array([6, 4, 2, 7, 0, 7, 4, 6, 7, 6])

3. How to find common values between two arrays?

In [47]:
x = np.random.randint(1, 10, 10)
y = np.random.randint(1, 10, 10)

In [55]:
np.intersect1d(x, y)

array([3, 4, 5])

4. Reverse a vector (first element becomes last)

In [57]:
x = np.arange(10)

In [58]:
x

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [59]:
x[::-1]

array([9, 8, 7, 6, 5, 4, 3, 2, 1, 0])

5. Create a 3x3 matrix with values ranging from 0 to 8

In [65]:
x = np.arange(9).reshape(3, 3)

In [66]:
x

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

6. Find indices of non-zero elements from the array [1,2,0,0,4,0]

In [74]:
x = np.array([1, 2, 0, 0, 4, 0])

In [80]:
np.nonzero(x)

(array([0, 1, 4], dtype=int64),)

7. Create a 3x3x3 array with random values

In [90]:
np.random.randn(3, 3, 3)

array([[[ 1.01191928, -0.85382563,  0.24864409],
        [ 0.41002186, -0.65421168, -0.78642399],
        [-0.58453627,  0.75991562, -1.0144923 ]],

       [[ 0.39635945, -0.810521  ,  0.29520641],
        [ 0.00822169, -0.49367855,  1.51825649],
        [-0.71446882, -0.23448663,  0.92948807]],

       [[-0.92798922, -0.92037083,  0.69015556],
        [ 1.12423118,  0.58749452, -1.92667888],
        [ 1.79078638, -2.0923607 ,  0.38945607]]])

8. Create a random vector of size 30 and find the mean value

In [81]:
x = np.random.randn(30)

In [83]:
x.mean()

0.012655054279473192

9. Create a 2d array with 1 on the border and 0 inside

In [111]:
x = np.ones([4, 5])

In [113]:
x

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [114]:
x[1:-1, 1:-1] = 0

In [115]:
x

array([[1., 1., 1., 1., 1.],
       [1., 0., 0., 0., 1.],
       [1., 0., 0., 0., 1.],
       [1., 1., 1., 1., 1.]])

10. Given an array x of 20 integers in the range (0, 100)

In [116]:
x = np.random.randint(0, 100, 20)
x

array([72,  4, 44, 10, 77, 24, 53, 51, 24, 80, 77,  2, 14,  0, 58,  4, 33,
        8, 32, 25])

and an random float in the range (0, 20)

In [117]:
y = np.random.uniform(0, 20)
y

13.895309890003515

Find the index of x where the value at that index is closest to y.

In [118]:
np.argmin(abs(x - y))

12